basePath: /
definitions:
  entity.Failure:
    properties:
      code:
        type: integer
      error: {}
      message:
        type: string
    type: object
  entity.User:
    properties:
      username:
        type: string
      uuid:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: ugur@extends.work
    name: API Support
  description: GoPress API Documentation
  license:
    name: MIT
    url: http://github.com/ugurkorkmaz/gopress
  termsOfService: http://github.com/ugurkorkmaz/gopress/
  title: GoPress API Documentation
  version: 0.0.1
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/entity.Failure'
            type: array
      summary: Register
      tags:
      - auth
swagger: "2.0"
